
ARTIFACTS_DIR : artifacts

DATA_INGESTION:
  ROOT_DIR : artifacts/data_ingestion
  SOURCE_URL: https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
  LOCAL_DATA_FILE: artifacts/data_ingestion/data.zip
  UNZIP_DIR : artifacts/data_ingestion


